import{S as m,i as l}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function p(s){const o="https://pixabay.com/api/",r=new URLSearchParams({key:"43019776-35548046cc937008d4e9556be",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),n=`${o}?${r}`;return fetch(n).then(e=>{if(!e)throw new Error("error");return e.json()}).then(e=>(console.log(e),e)).catch(e=>console.log("error"))}const i=document.querySelector(".gallery");function u(s){if(s.length==0)l.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight",width:"432px",height:"88px"});else{const o=s.map(r=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img class="photo" src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");i.insertAdjacentHTML("beforeend",o),f.refresh()}}const f=new m(".photos-list-link",{captionsData:"alt",captionDelay:250}),c=document.querySelector(".form");c.addEventListener("submit",h);function h(s){s.preventDefault(),i.innerHTML='<div class="loader"></div>';const o=c.elements.searchQuery.value.trim().toLowerCase();p(o).then(r=>{o===""?(i.innerHTML="",l.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight",width:"432px",height:"88px"})):(i.innerHTML="",u(r.hits)),c.reset()}).catch(r=>console.log("error"))}
//# sourceMappingURL=commonHelpers.js.map
